# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click !here goes the icon of the corresponding button in the gutter! button.
To debug a cell, press Alt+Shift+Enter, or click !here goes the icon of the corresponding button in the gutter! button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [24]:
import numpy as np

In [26]:
mylist = [1, 2, 3]
np.array(mylist)

array([1, 2, 3])

In [29]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
len(np.linspace(0, 10, 21))

21

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.random.rand(5, 5)

array([[0.70834952, 0.1892956 , 0.10626243, 0.60848403, 0.92231063],
       [0.00176055, 0.61915475, 0.84934171, 0.39786708, 0.71429048],
       [0.29642082, 0.64747686, 0.44866117, 0.29409005, 0.17968819],
       [0.23515491, 0.57083616, 0.24462432, 0.41447347, 0.94897781],
       [0.88345414, 0.21308714, 0.67419633, 0.24022406, 0.4623088 ]])

In [45]:
np.random.randn(5, 5)

array([[ 0.25141286, -0.77265793,  1.20763987, -1.24135922,  0.40109914],
       [ 0.68501882,  0.24015832, -0.10878557, -0.93351846,  0.37319337],
       [-2.02584094,  1.08706611,  1.36678161, -0.6927164 , -0.92986031],
       [ 0.15694337, -0.02739436,  0.08070192, -0.15349553, -0.72516423],
       [-2.05350408,  0.2415781 ,  1.03849379, -1.64111291,  1.13231704]])

In [53]:
np.random.seed(42)
np.random.randint(5, 100, (5, 5))

array([[56, 97, 19, 76, 65],
       [25, 87, 91, 79, 79],
       [92, 28,  7, 26, 57],
       [ 6, 92, 34, 42,  6],
       [68, 64, 25, 37, 80]])

In [54]:
np.random.seed(42)
np.random.randint(5, 100, (5, 5))

array([[56, 97, 19, 76, 65],
       [25, 87, 91, 79, 79],
       [92, 28,  7, 26, 57],
       [ 6, 92, 34, 42,  6],
       [68, 64, 25, 37, 80]])

In [55]:
np.random.rand(4)

array([0.61165316, 0.00706631, 0.02306243, 0.52477466])

In [57]:
arr = np.arange(0, 25)

In [60]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
ranarr = np.random.randint(0, 101, 10)

In [62]:
ranarr

array([41, 91, 59, 79, 14, 61, 61, 46, 61, 50])

In [64]:
ranarr.max()

91

In [65]:
ranarr.min()


14

In [66]:
ranarr.argmax()

1

In [67]:
myarray = np.linspace(0, 10, 101)

In [70]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


In [72]:
len(dice_rolls[dice_rolls > 2])

19